# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_dtscan_wrappers", use_symbols = TRUE, package_name = "dtscan")

#' @usage NULL
#' @useDynLib dtscan, .registration = TRUE
NULL

new_dtscan <- function() .Call(wrap__new_dtscan)

dtscan_delaunay <- function(obj) invisible(.Call(wrap__dtscan_delaunay, obj))

dtscan_preprocess <- function(obj, types, parallel) invisible(.Call(wrap__dtscan_preprocess, obj, types, parallel))

dtscan_run <- function(obj, min_pts, max_closeness) .Call(wrap__dtscan_run, obj, min_pts, max_closeness)

dtscan_set_points <- function(obj, x, y) invisible(.Call(wrap__dtscan_set_points, obj, x, y))


# nolint end
